version: "3"

services:
    fetus:
      build:
        context: .
      ports:
       - "8000:8000"
      volumes: 
       - ./fetus:/fetus
      command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"