version: "3"

services:
    fetus:
      build:
        context: .
      ports:
       - "8000:8000"
      volumes: 
       - ./fetus:/fetus
      command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
      environment:
        - DB_HOST=db
        - DB_NAME=fetus
        - DB_USER=postgres
        - DB_PASS=supersecretpassword
      depends_on: 
        - db


    db:
      image: postgres:12-alpine
      environment:
        - POSTGRES_DB=fetus
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword